# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_main/gui_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(867, 588)
        self.btn1 = QtWidgets.QPushButton(Form)
        self.btn1.setGeometry(QtCore.QRect(20, 10, 93, 28))
        self.btn1.setObjectName("btn1")
        self.btn1_2 = QtWidgets.QPushButton(Form)
        self.btn1_2.setGeometry(QtCore.QRect(20, 40, 93, 28))
        self.btn1_2.setObjectName("btn1_2")
        self.graphicsView = QtWidgets.QGraphicsView(Form)
        self.graphicsView.setGeometry(QtCore.QRect(190, 40, 561, 461))
        self.graphicsView.setObjectName("graphicsView")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn1.setText(_translate("Form", "btn1"))
        self.btn1_2.setText(_translate("Form", "btn2"))
